# Base URL for tests
webdriver.base.url = https://www.saucedemo.com/

# Browser settings
webdriver.driver = chrome
webdriver.chrome.driver = C:/Tejas/serenitybdd-framework-project/drivers/chromedriver.exe
webdriver.wait.for.timeout=20
serenity.take.screenshots = AFTER_EACH_STEP

# Reports
serenity.outputDirectory = target/site/serenity
serenity.project.name=Wesco Serenity Cucumber Automation Report
serenity.report.show.manual.tests=true
serenity.report.show.releases=true

#check dom
checkDom=true

#reporting
serenity.restart.browser.for.each=NEVER
serenity.clean.on.start=true
